// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eymzisihjdzlmgozvlfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5bXppc2loamR6bG1nb3p2bGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzQ3OTUsImV4cCI6MjA2MDIxMDc5NX0.Nwpo55xHxA-P8sD7JZa5kjq1Cu__AkpZAssY1Mzufe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);